import os
from PIL import Image
U='/mnt/user-data/uploads/';O='/home/claude/site/';os.makedirs(O+'img',exist_ok=True)
S={'hero':('IMG_20171206_223419.jpg',[800,1600]),'geste':('IMG_20171201_205907.jpg',[640,1100]),'macro':('IMG_20171120_195140.jpg',[640,1100]),'macro2':('IMG_20171008_004706.jpg',[640,1100]),
'khamsa':('IMG_20180205_191023.jpg',[640,1400]),'sol':('FB_IMG_1593428843080.jpg',[640,720]),'pilier':('FB_IMG_1511196809222.jpg',[640,720]),'arbre':('FB_IMG_1545820582355.jpg',[416]),'bordure':('FB_IMG_1536996295507.jpg',[640,720])}
D={}
for k,(f,ws) in S.items():
    im=Image.open(U+f).convert('RGB');W,H=im.size;ws=[w for w in ws if w<=W] or [W];D[k]=(W,H,ws)
    for w in ws: im.resize((w,round(H*w/W)),Image.LANCZOS).save(f'{O}img/{k}-{w}.webp',quality=78,method=6)
L=Image.open(U+'1622.png').convert('RGB');L.resize((900,900),Image.LANCZOS).save(O+'img/logo.webp',quality=82);L.resize((1200,1200)).save(O+'img/og.jpg',quality=82)
m=L.crop((330,150,950,770));[m.resize((s,s),Image.LANCZOS).save(O+n) for s,n in((32,'favicon-32.png'),(180,'apple-touch-icon.png'),(512,'icon-512.png'))]
def pic(k,alt,eager=False,sz='(min-width:900px) 33vw,100vw'):
    W,H,ws=D[k];a=f'../img/{k}-{ws[-1]}.webp'
    return f'<img src="{a}" srcset="'+','.join(f'../img/{k}-{w}.webp {w}w' for w in ws)+f'" sizes="{sz}" width="{ws[-1]}" height="{round(H*ws[-1]/W)}" alt="{alt}" data-full="{a}"'+(' fetchpriority="high"' if eager else ' loading="lazy" decoding="async"')+'>'
SITE='https://lithosimperial.com/';TEL='+39 351 386 6250';WA='393513866250'
T={
'fr':dict(t="LITHOS IMPERIAL — Mosaïste d'art, mosaïque sur mesure en pierre naturelle",d="Atelier d'art mosaïste à Camporosso Mare (Ligurie) : tableaux en mosaïque, fresques, sols, piscines et reproductions de mosaïques romaines et carthaginoises, faits main en pierre naturelle.",
 tag="Créations originales et reproductions façonnées à la main en pierre naturelle, inspirées des traditions de Carthage et de Rome.",sig="L'art de la mosaïque antique sur mesure",c1="Présenter mon projet",c2="Découvrir les œuvres",
 nav=["Œuvres","Sur mesure","Reproductions","L'atelier","Contact"],
 ih="Une œuvre commence par une pierre.",ip="Chaque mosaïque est assemblée comme une œuvre d'art. La matière, la découpe, l'orientation des tesselles et les irrégularités naturelles de la pierre font son caractère. De la petite pièce de collection à la composition monumentale, l'atelier réalise créations originales et reproductions, adaptées aux dimensions et à l'univers de votre projet.",
 wh="Les œuvres",wz="Cliquer pour examiner les détails",W=[("L'arbre de vie","Médaillon"),("Khamsa","Tableau"),("Sol aux poissons","Sol"),("Pilier aux entrelacs","Œuvre murale"),("Bordure végétale","Composition en cours")],
 cats=["Tableaux et pièces de collection","Œuvres murales et fresques","Sols, médaillons et compositions","Piscines, bassins et fontaines"],
 ch="Créer ce qui n'existe encore nulle part",cp="Une idée, une image, une émotion ou simplement une matière peuvent devenir une œuvre en mosaïque. L'atelier adapte le sujet, les dimensions, les matériaux et les nuances à votre projet.",steps=["Idée","Échange","Étude artistique","Choix des matériaux","Réalisation manuelle","Œuvre terminée"],
 rh="Les chefs-d'œuvre du passé, réinterprétés par la main du mosaïste",rp="Reproductions de mosaïques historiques et d'œuvres de référence, dans le respect de leur composition et de leurs détails, à la dimension de votre choix. Inspirées des traditions mosaïstes de Carthage et de Rome. Les œuvres anciennes du domaine public peuvent être reproduites librement ; une œuvre encore protégée par le droit d'auteur nécessite l'autorisation de ses ayants droit.",
 gh="La main avant la machine",gp="Chaque tesselle participe à l'œuvre. Les variations de couleur, de texture et de veinage ne sont pas des défauts à effacer : elles font la personnalité de la matière. Taillées et posées une à une, à la main.",
 ah="Dans l'atelier",ap="Kosta Imed LITHOS, artisan mosaïste, crée des œuvres en mosaïque sur mesure à Camporosso Mare (Ligurie). Il collabore, lorsque le projet le demande, avec propriétaires, architectes, décorateurs et designers : vous imaginez l'espace, l'atelier réalise la mosaïque.",
 ph="Présenter mon projet",pp="Une idée, une image, un espace ? Décrivez-le : chaque demande est étudiée individuellement par l'atelier.",fl=["Votre nom","Type d'œuvre","Dimensions approximatives","Décrivez votre idée ou l'espace concerné"],
 opts=["Tableau","Œuvre murale / fresque","Sol / médaillon","Piscine / fontaine","Reproduction","Autre"],send="Présenter mon projet à l'atelier",note="Le message s'ouvre dans WhatsApp, vous pouvez y joindre photos et plans. Ce site n'enregistre aucune donnée.",wa="Bonjour, je souhaite présenter un projet à LITHOS IMPERIAL.",
 lh="Mentions légales et confidentialité",lp=["Éditeur : Kosta Imed LITHOS, atelier LITHOS IMPERIAL, Camporosso Mare (IM), Italie. Tél. +39 351 386 6250. N° TVA / P.IVA : [à compléter]. Hébergement : GitHub Pages (GitHub, Inc., États-Unis).","Confidentialité (RGPD, règlement UE 2016/679) : ce site n'utilise ni cookies ni outil de suivi et ne collecte aucune donnée. Le formulaire prépare simplement un message WhatsApp que vous envoyez vous-même ; l'hébergeur peut journaliser votre adresse IP pour la sécurité. Vos droits d'accès, de rectification et d'effacement s'exercent auprès de l'atelier ; vous pouvez saisir le Garante per la protezione dei dati personali.","Les œuvres et photographies présentées sont la propriété de l'atelier ; toute reproduction sans autorisation est interdite."],pv="Contact"),
'en':dict(t="LITHOS IMPERIAL — Mosaic artist, bespoke handcrafted stone mosaics",d="Mosaic art atelier in Camporosso Mare (Liguria, Italy): bespoke mosaic artworks, murals, floors, pools and reproductions of Roman and Carthaginian mosaics, handmade in natural stone.",
 tag="Original creations and reproductions shaped by hand in natural stone, inspired by the traditions of Carthage and Rome.",sig="The art of antique mosaic, made to measure",c1="Present my project",c2="Discover the works",
 nav=["Works","Bespoke","Reproductions","The atelier","Contact"],
 ih="A work begins with a stone.",ip="Every mosaic is assembled as a work of art. The material, the cut, the direction of the tesserae and the natural irregularities of the stone give it character. From a small collector's piece to a monumental composition, the atelier creates original works and reproductions, fitted to the size and spirit of your project.",
 wh="The works",wz="Click to examine the details",W=[("The tree of life","Medallion"),("Khamsa","Panel"),("Floor with fish","Floor"),("Pillar with knotwork","Mural work"),("Foliate border","Work in progress")],
 cats=["Panels and collector's pieces","Murals and frescoes","Floors, medallions and compositions","Pools, basins and fountains"],
 ch="Create what does not exist yet",cp="An idea, an image, an emotion or simply a material can become a mosaic artwork. The atelier adapts subject, dimensions, materials and shades to your project.",steps=["Idea","Conversation","Artistic study","Choice of materials","Handmade execution","Finished work"],
 rh="Masterpieces of the past, reinterpreted by the mosaicist's hand",rp="Reproductions of historic mosaics and reference works, faithful to their composition and detail, at the size you choose. Inspired by the mosaic traditions of Carthage and Rome. Ancient public-domain works may be reproduced freely; a work still under copyright requires permission from the rights holders.",
 gh="The hand before the machine",gp="Every tessera shapes the work. Variations in colour, texture and veining are not flaws to erase: they are the personality of the stone. Cut and set one by one, by hand.",
 ah="In the atelier",ap="Kosta Imed LITHOS, mosaic craftsman, creates bespoke mosaic artworks in Camporosso Mare (Liguria). When a project calls for it, he works with owners, architects, decorators and designers: you imagine the space, the atelier makes the mosaic.",
 ph="Present my project",pp="An idea, an image, a space? Describe it: every request is studied individually by the atelier.",fl=["Your name","Type of work","Approximate dimensions","Describe your idea or the space"],
 opts=["Panel","Mural / fresco","Floor / medallion","Pool / fountain","Reproduction","Other"],send="Present my project to the atelier",note="The message opens in WhatsApp, where you can attach photos and plans. This site stores no data.",wa="Hello, I would like to present a project to LITHOS IMPERIAL.",
 lh="Legal notice and privacy",lp=["Publisher: Kosta Imed LITHOS, atelier LITHOS IMPERIAL, Camporosso Mare (IM), Italy. Tel. +39 351 386 6250. VAT / P.IVA: [to be completed]. Hosting: GitHub Pages (GitHub, Inc., USA).","Privacy (GDPR, EU Regulation 2016/679): this site uses no cookies or tracking and collects no data. The form only prepares a WhatsApp message that you send yourself; the host may log your IP address for security. You may exercise your rights of access, rectification and erasure with the atelier, or contact the Italian Garante per la protezione dei dati personali.","The works and photographs shown belong to the atelier; reproduction without permission is prohibited."],pv="Contact"),
'it':dict(t="LITHOS IMPERIAL — Mosaicista d'arte, mosaici su misura in pietra naturale",d="Atelier di mosaico artistico a Camporosso Mare (Liguria): quadri, murali, pavimenti, piscine e riproduzioni di mosaici romani e cartaginesi, fatti a mano in pietra naturale.",
 tag="Creazioni originali e riproduzioni modellate a mano in pietra naturale, ispirate alle tradizioni di Cartagine e di Roma.",sig="L'arte del mosaico antico su misura",c1="Presenta il tuo progetto",c2="Scopri le opere",
 nav=["Opere","Su misura","Riproduzioni","L'atelier","Contatto"],
 ih="Un'opera comincia da una pietra.",ip="Ogni mosaico è composto come un'opera d'arte. La materia, il taglio, l'orientamento delle tessere e le irregolarità naturali della pietra ne fanno il carattere. Dal piccolo pezzo da collezione alla composizione monumentale, l'atelier realizza creazioni originali e riproduzioni, adatte alle dimensioni e allo spirito del progetto.",
 wh="Le opere",wz="Clicca per esaminare i dettagli",W=[("L'albero della vita","Medaglione"),("Khamsa","Quadro"),("Pavimento con pesci","Pavimento"),("Pilastro a intrecci","Opera murale"),("Bordo vegetale","Composizione in corso")],
 cats=["Quadri e pezzi da collezione","Opere murali e affreschi","Pavimenti, medaglioni e composizioni","Piscine, vasche e fontane"],
 ch="Creare ciò che ancora non esiste",cp="Un'idea, un'immagine, un'emozione o semplicemente una materia possono diventare un mosaico. L'atelier adatta soggetto, dimensioni, materiali e sfumature al tuo progetto.",steps=["Idea","Confronto","Studio artistico","Scelta dei materiali","Realizzazione a mano","Opera finita"],
 rh="I capolavori del passato, reinterpretati dalla mano del mosaicista",rp="Riproduzioni di mosaici storici e opere di riferimento, fedeli a composizione e dettagli, nella dimensione desiderata. Ispirate alle tradizioni musive di Cartagine e di Roma. Le opere antiche di pubblico dominio si possono riprodurre liberamente; un'opera ancora protetta dal diritto d'autore richiede l'autorizzazione degli aventi diritto.",
 gh="La mano prima della macchina",gp="Ogni tessera partecipa all'opera. Le variazioni di colore, texture e venatura non sono difetti da cancellare: sono la personalità della materia. Tagliate e posate una a una, a mano.",
 ah="Nell'atelier",ap="Kosta Imed LITHOS, artigiano mosaicista, crea opere in mosaico su misura a Camporosso Mare (Liguria). Quando il progetto lo richiede collabora con proprietari, architetti, decoratori e designer: voi immaginate lo spazio, l'atelier realizza il mosaico.",
 ph="Presenta il tuo progetto",pp="Un'idea, un'immagine, uno spazio? Descrivilo: ogni richiesta è valutata singolarmente dall'atelier.",fl=["Il tuo nome","Tipo di opera","Dimensioni approssimative","Descrivi l'idea o lo spazio"],
 opts=["Quadro","Opera murale / affresco","Pavimento / medaglione","Piscina / fontana","Riproduzione","Altro"],send="Presenta il progetto all'atelier",note="Il messaggio si apre in WhatsApp, dove puoi allegare foto e planimetrie. Questo sito non salva alcun dato.",wa="Buongiorno, vorrei presentare un progetto a LITHOS IMPERIAL.",
 lh="Note legali e privacy",lp=["Editore: Kosta Imed LITHOS, atelier LITHOS IMPERIAL, Camporosso Mare (IM), Italia. Tel. +39 351 386 6250. P.IVA: [da completare]. Hosting: GitHub Pages (GitHub, Inc., USA).","Privacy (GDPR, Reg. UE 2016/679): il sito non usa cookie né strumenti di tracciamento e non raccoglie dati. Il modulo prepara soltanto un messaggio WhatsApp che invii tu stesso; l'host può registrare l'indirizzo IP per sicurezza. Puoi esercitare i diritti di accesso, rettifica e cancellazione presso l'atelier o rivolgerti al Garante per la protezione dei dati personali.","Opere e fotografie sono di proprietà dell'atelier; ne è vietata la riproduzione senza autorizzazione."],pv="Contatto")}
CSS="""*{box-sizing:border-box;margin:0}html{scroll-behavior:smooth;scroll-padding-top:4rem}@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}}
:root{--k:#0f0d0b;--i:#f2ede2;--t:#d8ceb8;--g:#8b857a;--b:#4b4034;--o:#a88f58}
body{background:var(--k);color:var(--i);font:17px/1.65 system-ui,-apple-system,"Segoe UI",Roboto,sans-serif}
h1,h2,h3,.brand{font-family:"Iowan Old Style","Palatino Linotype",Palatino,"Book Antiqua",Georgia,serif;font-weight:400;line-height:1.15}
a{color:inherit}:focus-visible{outline:2px solid var(--o);outline-offset:3px}
header{position:fixed;inset:0 0 auto;z-index:5;display:flex;gap:1rem;align-items:center;justify-content:space-between;padding:.8rem 5vw;background:linear-gradient(#0f0d0bd9,#0f0d0b00)}
.brand{text-decoration:none;font-size:1.15rem;letter-spacing:.14em;display:flex;align-items:center;gap:.6rem}.brand img{width:34px;height:34px}
nav{display:flex;gap:1.4rem;font-size:.9rem}nav a{text-decoration:none;opacity:.85}nav a:hover{opacity:1}.lang{font-size:.85rem;display:flex;gap:.6rem}.lang a{text-decoration:none;opacity:.6}.lang a[aria-current]{opacity:1;color:var(--o)}
@media(max-width:860px){nav{display:none}}
.hero{position:relative;min-height:100svh;display:grid;align-content:end;padding:0 5vw 12vh}.hero>img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;z-index:-1}
.hero:before{content:"";position:absolute;inset:0;background:linear-gradient(#0f0d0b66,#0f0d0bf2 88%);z-index:-1}
h1{font-size:clamp(2.4rem,7vw,5.5rem);letter-spacing:.06em}.sig{font-size:1.1rem;letter-spacing:.06em;color:var(--o);margin:.6rem 0 1rem}.tag{max-width:36rem;color:var(--t)}
.btns{display:flex;flex-wrap:wrap;gap:.8rem;margin-top:1.8rem}.btn{display:inline-block;padding:.9rem 1.5rem;border:1px solid var(--o);text-decoration:none;font-size:.85rem;letter-spacing:.1em;text-transform:uppercase;background:none;color:var(--i);cursor:pointer;font-family:inherit}.btn.p{background:var(--o);color:var(--k)}.btn:hover{filter:brightness(1.12)}
section{padding:clamp(3.5rem,9vw,7rem) 5vw}.light{background:var(--i);color:var(--k)}.light .btn{color:var(--k)}
h2{font-size:clamp(1.8rem,4vw,3rem);max-width:22ch;margin-bottom:1.2rem}.wrap{max-width:46rem}.light p,.wrap p{color:inherit}.dim{color:var(--t)}
.grid{display:grid;gap:1rem;grid-template-columns:repeat(auto-fill,minmax(min(100%,16rem),1fr));margin:2rem 0}
figure{margin:0;position:relative;background:#000}figure img{display:block;width:100%;aspect-ratio:4/5;object-fit:cover;cursor:zoom-in}figcaption{padding:.6rem .2rem;font-size:.9rem;color:var(--t)}figcaption b{font-weight:400;display:block;color:var(--i);font-family:Georgia,serif;font-size:1.05rem}
.cats{list-style:none;padding:0;display:grid;gap:.4rem;margin-top:1rem;color:var(--t)}
ol{padding-left:1.2rem;display:grid;gap:.3rem;margin:1.2rem 0}.geste{display:grid;gap:1rem;grid-template-columns:repeat(auto-fit,minmax(min(100%,14rem),1fr));margin-top:2rem}.geste img{width:100%;height:100%;max-height:26rem;object-fit:cover;display:block}
form{display:grid;gap:.9rem;max-width:36rem;margin-top:1.5rem}input,select,textarea{width:100%;padding:.8rem;background:#1b1814;color:var(--i);border:1px solid var(--b);font:inherit}textarea{min-height:7rem}label{font-size:.85rem;color:var(--t);display:grid;gap:.3rem}.small{font-size:.85rem;color:var(--g)}
footer{padding:2.5rem 5vw 6rem;font-size:.85rem;color:var(--g)}footer p{max-width:60rem;margin-top:.7rem}
.fab{position:fixed;right:1rem;bottom:1rem;z-index:6;padding:.75rem 1.2rem;background:var(--k);border:1px solid var(--o);font-size:.78rem;letter-spacing:.1em;text-transform:uppercase;text-decoration:none}
dialog{border:0;background:#000e;max-width:100vw;max-height:100vh;width:100%;height:100%;padding:0}dialog::backdrop{background:#000}.lb{width:100%;height:100%;overflow:auto;display:grid;place-items:center}.lb img{max-width:100%;max-height:100vh;cursor:zoom-in;transition:transform .2s}.lb img.z{transform:scale(2.6);cursor:zoom-out}
dialog button{position:fixed;top:.8rem;right:1rem;z-index:2;background:var(--k);color:var(--i);border:1px solid var(--o);padding:.5rem .9rem;cursor:pointer}"""
JS="""var d=document,lb=d.getElementById('lb'),li=lb.querySelector('img');
d.querySelectorAll('figure img').forEach(function(i){i.onclick=function(){li.src=i.dataset.full;li.alt=i.alt;li.className='';lb.showModal()}});
li.onclick=function(e){var r=li.getBoundingClientRect();li.style.transformOrigin=(e.clientX-r.left)/r.width*100+'% '+(e.clientY-r.top)/r.height*100+'%';li.classList.toggle('z')};
lb.querySelector('button').onclick=function(){lb.close()};
d.querySelectorAll('.lang a').forEach(function(a){a.onclick=function(){try{localStorage.lang=a.hreflang}catch(e){}}});
var f=d.getElementById('pf');f.onsubmit=function(e){e.preventDefault();var v=[].map.call(f.elements,function(x){return x.name&&x.value?x.value:''}).filter(Boolean);open('https://wa.me/WAWA?text='+encodeURIComponent(f.dataset.wa+'\\n'+v.join('\\n')))}""".replace("WAWA",WA)
ORD=['arbre','khamsa','sol','pilier','bordure']
import json
for lg,c in T.items():
    os.makedirs(O+lg,exist_ok=True)
    alts=[f'{a}, {b} — LITHOS IMPERIAL' for a,b in c['W']]
    figs=''.join(f'<figure>{pic(k,alts[i])}<figcaption><b>{c["W"][i][0]}</b>{c["W"][i][1]}</figcaption></figure>' for i,k in enumerate(ORD))
    hl=''.join(f'<link rel="alternate" hreflang="{x}" href="{SITE}{x}/">' for x in T)+f'<link rel="alternate" hreflang="x-default" href="{SITE}">'
    ld='{"@context":"https://schema.org","@type":"LocalBusiness","name":"LITHOS IMPERIAL","description":%s,"url":"%s%s/","image":"%simg/og.jpg","telephone":"%s","founder":{"@type":"Person","name":"Kosta Imed LITHOS"},"address":{"@type":"PostalAddress","addressLocality":"Camporosso Mare","addressRegion":"Imperia","addressCountry":"IT"},"knowsLanguage":["fr","en","it"]}'%(json.dumps(c['d'],ensure_ascii=False),SITE,lg,SITE,TEL)
    langs=''.join(f'<a href="../{x}/" hreflang="{x}" lang="{x}"'+(' aria-current="page"' if x==lg else '')+f'>{x.upper()}</a>' for x in T)
    n=c['nav']
    html=f'''<!doctype html><html lang="{lg}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{c['t']}</title><meta name="description" content="{c['d']}"><link rel="canonical" href="{SITE}{lg}/">{hl}<meta name="theme-color" content="#0f0d0b"><link rel="icon" href="../favicon-32.png" sizes="32x32"><link rel="apple-touch-icon" href="../apple-touch-icon.png"><meta property="og:type" content="website"><meta property="og:title" content="{c['t']}"><meta property="og:description" content="{c['d']}"><meta property="og:image" content="{SITE}img/og.jpg"><meta property="og:url" content="{SITE}{lg}/"><meta name="twitter:card" content="summary_large_image"><script type="application/ld+json">{ld}</script><style>{CSS}</style></head><body>
<header><a class="brand" href="#top"><img src="../favicon-32.png" width="34" height="34" alt="">LITHOS IMPERIAL</a><nav><a href="#oeuvres">{n[0]}</a><a href="#sur-mesure">{n[1]}</a><a href="#reproductions">{n[2]}</a><a href="#atelier">{n[3]}</a><a href="#projet">{n[4]}</a></nav><div class="lang">{langs}</div></header>
<main id="top"><section class="hero">{pic('hero','LITHOS IMPERIAL — '+c['sig'],True,'100vw')}<h1>LITHOS IMPERIAL</h1><p class="sig">{c['sig']}</p><p class="tag">{c['tag']}</p><div class="btns"><a class="btn p" href="#projet">{c['c1']}</a><a class="btn" href="#oeuvres">{c['c2']}</a></div></section>
<section class="light"><div class="wrap"><h2>{c['ih']}</h2><p>{c['ip']}</p></div></section>
<section id="oeuvres"><h2>{c['wh']}</h2><p class="small">{c['wz']}</p><div class="grid">{figs}</div><ul class="cats">{''.join(f'<li>{x}</li>' for x in c['cats'])}</ul></section>
<section id="sur-mesure" class="light"><div class="wrap"><h2>{c['ch']}</h2><p>{c['cp']}</p><ol>{''.join(f'<li>{s}</li>' for s in c['steps'])}</ol><a class="btn" href="#projet">{c['c1']}</a></div></section>
<section id="reproductions"><div class="wrap"><h2>{c['rh']}</h2><p class="dim">{c['rp']}</p></div></section>
<section id="atelier" class="light"><div class="wrap"><h2>{c['gh']}</h2><p>{c['gp']}</p></div><div class="geste">{pic('geste','Mosaïste — LITHOS IMPERIAL','','(min-width:900px) 33vw,100vw').replace('data-full','data-x')}{pic('macro','Tesselles, pierre naturelle').replace('data-full','data-x')}{pic('macro2','Tesselles, pierre naturelle').replace('data-full','data-x')}</div><div class="wrap" style="margin-top:3rem"><h2>{c['ah']}</h2><p>{c['ap']}</p></div></section>
<section id="projet"><div class="wrap"><h2>{c['ph']}</h2><p class="dim">{c['pp']}</p>
<form id="pf" data-wa="{c['wa']}"><label>{c['fl'][0]}<input name="n" autocomplete="name" required></label><label>{c['fl'][1]}<select name="t">{''.join(f'<option>{o}</option>' for o in c['opts'])}</select></label><label>{c['fl'][2]}<input name="s"></label><label>{c['fl'][3]}<textarea name="m" required></textarea></label><button class="btn p" type="submit">{c['send']}</button><p class="small">{c['note']}</p></form>
<p style="margin-top:1.5rem"><a href="https://wa.me/{WA}">WhatsApp</a> · <a href="tel:+393513866250">{TEL}</a></p><p class="small">Camporosso Mare, Imperia, Italia</p></div></section></main>
<footer><h3>{c['lh']}</h3>{''.join(f'<p>{x}</p>' for x in c['lp'])}<p>© LITHOS IMPERIAL</p></footer>
<a class="fab" href="#projet">{c['c1']}</a><dialog id="lb"><button aria-label="Close">✕</button><div class="lb"><img alt=""></div></dialog><script>{JS}</script></body></html>'''
    open(O+lg+'/index.html','w').write(html)
open(O+'index.html','w').write(f'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>LITHOS IMPERIAL</title><meta name="description" content="{T["en"]["d"]}"><link rel="canonical" href="{SITE}">{hl}<script>try{{var l=(localStorage.lang||navigator.language||"en").slice(0,2).toLowerCase();if(!/^(fr|en|it)$/.test(l))l="en";location.replace(l+"/"+location.hash)}}catch(e){{location.replace("en/")}}</script></head><body style="background:#0f0d0b;color:#f2ede2;font-family:sans-serif;text-align:center;padding:4rem"><h1>LITHOS IMPERIAL</h1><p><a href="fr/">Français</a> · <a href="en/">English</a> · <a href="it/">Italiano</a></p></body></html>')
open(O+'robots.txt','w').write(f'User-agent: *\nAllow: /\nSitemap: {https://maxmcneil.github.io/Lithos-IMPERIAL/}sitemap.xml\n')
open(O+'sitemap.xml','w').write('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">'+''.join(f'<url><loc>{SITE}{x}/</loc>'+''.join(f'<xhtml:link rel="alternate" hreflang="{y}" href="{SITE}{y}/"/>' for y in T)+'</url>' for x in T)+'</urlset>')
open(O+'.nojekyll','w').write('')
open(O+'README.md','w').write('# LITHOS IMPERIAL\nSite statique (FR/EN/IT). Déploiement: dépôt GitHub > Settings > Pages > Branch main / root. Remplacer `https://lithosimperial.com/` (build.py: SITE) par l\'URL réelle, puis `python3 build.py`. Compléter la P.IVA dans les mentions légales.\n')
